baseURL = "https://myselfHimanshu.github.io/"
languageCode = "en-us"
title = "Data Summit"
theme = "hyde"

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = "myselfhimanshu-github-io"

[Menus]
  main = [
      {Name = "LinkedIn", URL = "https://www.linkedin.com/in/047himanshu/"},
      {Name = "Github", URL = "https://github.com/myselfhimanshu/"},
      {Name = "Twitter", URL = "https://twitter.com/047himanshu"}
  ]


[params]
  #description = "I am Deep Learning practioner. I blog about Machine Learning, Deep Learning, Computer Vision and Natural Language Processing."
  description = "Everything started as nothing."
  themeColor = "theme-base-08"
